### ISSUE TITLE
[21w39a] No ores spawning

### ISSUE THREAD

**Issue by kwpugh** [yaeyewon112/YMetalLib-fabric#2]
Didn't try 21w38a, but I expect same result since nothing changed with ore spawn between snapshots.

**Comment by kwpugh** [comment]
I was playing around with your source code and got it working in 21w39a

![2021-10-02_16 32 25](https://user-images.githubusercontent.com/8809210/135732326-6b027a13-471f-4e99-9f37-4f16dd4f4ac3.png)

**Comment by kwpugh** [comment]
fixed version on GitHub

**Comment by Hye0Ngit** [comment]
Fixed on 1.3.5 :)
