### ISSUE TITLE
[21w39a] Suggestion: Can ores drop items instead of blocks?

### ISSUE THREAD

**Issue by kwpugh** [yaeyewon112/YMetalLib-fabric#3]
Hi,

I've been playing with your mod in 21w39a, so far so good.

Since 1.17, vanilla switched metal ores to dropping raw instead of blocks, leaving blocks for silk touch only.  Most mods have switched over to dropping raw metal or gems from the ores.

Just a thought.

Regards.

**Comment by kwpugh** [comment]
Additional thought, instead of using the hammer on smelted ingots, might make more sense to use hammer on raw drops to get powder.

I assume you already know the hammer only gets one use.

**Comment by kwpugh** [comment]
I did some work on  the mod and sharing my version:

https://github.com/kwpugh/YMetalLib-fabric-1.18.x-ex

List of  changes:
- restructured into packages instead of one, big main class
- fixed ore gen in overworld, nether, and end (using mixins into vanilla methods)
- added tag support for my Resourceful Tools, which  takes damage and stays in crafting grid

I'm just playing with this locally, I have no intent to publish.  If you wish to use this version as a base, feel, otherwise,  disregard.

Cheers

**Comment by kwpugh** [comment]
Adjusted hammer and wrench to stay in grid, their recipes now produce 1 instead of 64 since they don't disappear

**Comment by Hye0Ngit** [comment]
Oh wait, I didn't shared mod version 1.3.5-ex for 21w39a, but how did you played on 21w39a?

**Comment by kwpugh** [comment]
I downloaded a copy and updated it for locally playing around.  https://github.com/kwpugh/YMetalLib-fabric-1.18.x-ex

**Comment by kwpugh** [comment]
That version has raw metal drops and a bunch of fixes.  It is yours to do what you want with.  If you don't want it, let me know and I will take it back down.  I was just using for some testing/playing around one my end.

**Comment by kwpugh** [comment]
I also downgraded the java ver to 16, it appears the new fabric server loader does not support java 17.

**Comment by Hye0Ngit** [comment]
Are you Korean?

**Comment by Hye0Ngit** [comment]
This code is great, but why you didn't fork, just download and upload? So I can't merge.

**Comment by kwpugh** [comment]
I'm American, in the Midwest of USA.

Sorry I didn't fork.  I originally just figured I was going to play with it locally.

**Comment by kwpugh** [comment]
if you haven't been updating your version, you can download my copy and import into IDE

**Comment by Hye0Ngit** [comment]
I am already developing 1.3.5-ex, which adds Tungsten, so sadly I cannot merge...

**Comment by kwpugh** [comment]
I'll close this out since it is in your court now.   Would you prefer that I take my copy down at this point?

**Comment by Hye0Ngit** [comment]
Where's the source? (1.3.5-ex cancelled because 1.18 officially released)

**Comment by kwpugh** [comment]
I  took my version down, its your mod.

**Comment by Hye0Ngit** [comment]
https://github.com/kwpugh/YMetalLib-fabric not exists

**Comment by kwpugh** [comment]
yeah, that is what I said, I deleted it from my GitHub, I was done with it.
